--1.partition table query larger than 10M
SELECT TOP (1000) [ID]
      ,[TableName]
      ,[SchemaName]
      ,[rows]
      ,[IsPartitioned]
      ,[PartitionCount]
      ,[ContainsLOBs]
      ,[ConcatenatedLOBs]
      ,[CountLess1KAndNulls]
      ,[MaxLOBSizeKB]
      ,[AvgSizeKB]
      ,[MinSizeKB]
      ,[MaxSizeMB]
      ,[AvgSizeMB]
      ,[MinSizeMB]
      ,[TableSize]
      ,[Type]
      ,[Table_JSON]
  FROM [DemoDB].[dbo].[ActMigListTables] where [IsPartitioned] = 'Partitioned' and rows > 10000000


--2.Non partition table query larger than 10M
SELECT TOP (1000) [ID]
      ,[TableName]
      ,[SchemaName]
      ,[rows]
      ,[IsPartitioned]
      ,[PartitionCount]
      ,[ContainsLOBs]
      ,[ConcatenatedLOBs]
      ,[CountLess1KAndNulls]
      ,[MaxLOBSizeKB]
      ,[AvgSizeKB]
      ,[MinSizeKB]
      ,[MaxSizeMB]
      ,[AvgSizeMB]
      ,[MinSizeMB]
      ,[TableSize]
      ,[Type]
      ,[Table_JSON]
  FROM [DemoDB].[dbo].[ActMigListTables] where [IsPartitioned] = 'Not Partitioned' and rows > 10000000

--3.LOB tables query larger than 1k
SELECT TOP (1000) [ID]
      ,[TableName]
      ,[SchemaName]
      ,[rows]
      ,[IsPartitioned]
      ,[PartitionCount]
      ,[ContainsLOBs]
      ,[ConcatenatedLOBs]
      ,[CountLess1KAndNulls]
      ,[MaxLOBSizeKB]
      ,[AvgSizeKB]
      ,[MinSizeKB]
      ,[MaxSizeMB]
      ,[AvgSizeMB]
      ,[MinSizeMB]
      ,[TableSize]
      ,[Type]
      ,[Table_JSON]
  FROM [DemoDB].[dbo].[ActMigListTables] where MaxLOBSizeKB > 1


--4.remaining tables query
SELECT TOP (1000) [ID]
      ,[TableName]
      ,[SchemaName]
      ,[rows]
      ,[IsPartitioned]
      ,[PartitionCount]
      ,[ContainsLOBs]
      ,[ConcatenatedLOBs]
      ,[CountLess1KAndNulls]
      ,[MaxLOBSizeKB]
      ,[AvgSizeKB]
      ,[MinSizeKB]
      ,[MaxSizeMB]
      ,[AvgSizeMB]
      ,[MinSizeMB]
      ,[TableSize]
      ,[Type]
      ,[Table_JSON]
  FROM [DemoDB].[dbo].[ActMigListTables] where MaxLOBSizeKB < 1 and ([IsPartitioned] = 'Not Partitioned' and rows < 10000000 or [IsPartitioned] = 'Partitioned' and rows < 10000000)

