--3.LOB tables query larger than 1k
SELECT TOP (1000) [ID]
      ,[TableName]
      ,[SchemaName]
      ,[rows]
      ,[IsPartitioned]
      ,[PartitionCount]
      ,[ContainsLOBs]
      ,[ConcatenatedLOBs]
      ,[CountLess1KAndNulls]
      ,[MaxLOBSizeKB]
      ,[AvgSizeKB]
      ,[MinSizeKB]
      ,[MaxSizeMB]
      ,[AvgSizeMB]
      ,[MinSizeMB]
      ,[TableSize]
      ,[Type]
      ,[Table_JSON]
  FROM [{{db_name}}].[dbo].[ActMigListTables] where MaxLOBSizeKB > 1