--4.remaining tables query
SELECT TOP (1000) [ID]
      ,[TableName]
      ,[SchemaName]
      ,[rows]
      ,[IsPartitioned]
      ,[PartitionCount]
      ,[ContainsLOBs]
      ,[ConcatenatedLOBs]
      ,[CountLess1KAndNulls]
      ,[MaxLOBSizeKB]
      ,[AvgSizeKB]
      ,[MinSizeKB]
      ,[MaxSizeMB]
      ,[AvgSizeMB]
      ,[MinSizeMB]
      ,[TableSize]
      ,[Type]
      ,[Table_JSON]
  FROM [{{db_name}}].[dbo].[ActMigListTables] where MaxLOBSizeKB > 1 or ([IsPartitioned] = 'Not Partitioned' and rows > 10000000 or [IsPartitioned] = 'Partitioned' and rows > 10000000)
